# gemma_mobile_app/pubspec.yaml
name: gemma_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your SDK constraints

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.10.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0 # Make sure you have this dependency

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  # The assets section is not needed for this approach