name: gemma_mobile_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0' # Adjust to your SDK constraints

dependencies:
  flutter:
    sdk: flutter
  flutter_gemma: ^0.10.0
  path_provider: ^2.1.5
  permission_handler: ^11.4.0
  cupertino_icons: ^1.0.8
  
  # ObjectBox dependencies for local database
  objectbox: ^4.3.0
  objectbox_flutter_libs: any
  
  # State management
  provider: ^6.0.5
  
  # Optional: For path manipulation when setting up ObjectBox store
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # ObjectBox code generation
  build_runner: ^2.4.11
  objectbox_generator: any

flutter:
  uses-material-design: true